schema_version = "1.0.0"
id = "tris_to_quads_ex"
version = "1.3.0"
name = "Optimized Tris to Quads Converter"
tagline = "Convert triangles to quads using mathematical optimization"
maintainer = "Rulesobeyer <https://github.com/Rulesobeyer/>"
type = "add-on"
blender_version_min = "4.2.0"
license = [
    "SPDX:GPL-3.0-or-later",
]
tags = ["Mesh"]
website = "https://github.com/Rulesobeyer/Tris-Quads-Ex"
[permissions]
network = "Required to download and install the PuLP optimization library"
